data_config: 
  raw_csv: data/raw/train.csv
  num_cols: ['Age','Annual_Income', 'Monthly_Inhand_Salary', 'Num_Bank_Accounts', 'Num_Credit_Card', 'Num_of_Loan', 'Interest_Rate', 'Delay_from_due_date', 'Credit_Utilization_Ratio', 'Monthly_Balance', 'Outstanding_Debt']
  cat_cols: ['Occupation']
  target: Credit_Score
  random_state: 42
  train_csv: data/processed/train.csv
  test_csv: data/processed/test.csv

mlflow_config:
  artifacts_dir: artifacts
  experiment_name: model_iteration1
  run_name: catboost
  registered_model_name: catboost_model
  remote_server_uri: http://localhost:4321

classifier:
  depth: 4
  learning_rate: 0.01
  iterations: 500


model_dir: models/model.joblib   